### ISSUE TITLE
Win11下不生效

### ISSUE THREAD

**Issue by moemoli** [way-zer/IME_Fixer#2]
这是win11的msctf.dll

https://lliiooll.lanzouy.com/iWxCOzlfowh

与win10的有大小差异

![图片](https://user-images.githubusercontent.com/44719954/152545126-6ac359c9-2ea5-462e-8711-d1be1690e986.png)

**Comment by way-zer** [comment]
我研究了下,dll破解点位和win10的没有区别. 你现在是什么现象? 有崩溃吗? 候选框有吗? 拼词框有吗?

**Comment by moemoli** [comment]
> 

直接和没装一样，看了下日志，输出的两个都是false

![图片](https://user-images.githubusercontent.com/44719954/152638494-89643735-5b07-43bd-8d8e-87a32ae3832e.png)

**Comment by way-zer** [comment]
看日记，应该是Foo端的问题，Window是通过窗口标题查找的，Foo端改了标题，找不到窗口

**Comment by way-zer** [comment]
我试试从arc那边取window句柄

**Comment by way-zer** [comment]
v1.3.2已修复.
