### ISSUE TITLE
打字时无候选框

### ISSUE THREAD

**Issue by moemoli** [way-zer/IME_Fixer#3]
![图片](https://user-images.githubusercontent.com/44719954/154794075-540aabba-895b-4258-ba35-1507d75b3875.png)

系统是win10 x64专业版

**Comment by way-zer** [comment]
这个是已知问题，不是bug。
## 解决方法：
* 开启游戏时，不要开启中文输入法。
* 通过切换关闭输入法，切换焦点到其他程序，再切换回来，开启输入法。
## 内部原因：
* 游戏在MOD加载前，处理了输入法的事件，让输入法进入了隐藏状态，此时MOD没有办法使其恢复。需要输入法重新发出事件。

**Comment by moemoli** [comment]
好的，谢谢
